global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using OnlineBookStore.Common.Application;
global using System.Threading.Tasks;
global using BookMS.Domain.Entites;
global using Microsoft.EntityFrameworkCore;
global using Serilog;